# Generated by Django 2.2.3 on 2019-07-25 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_key', models.CharField(max_length=50, unique=True)),
                ('archived', models.BooleanField(default=False)),
                ('date_bookmarked', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('resource_key', models.CharField(max_length=50, unique=True)),
                ('archived', models.BooleanField(default=False)),
                ('date_commented', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_heading', models.CharField(max_length=100)),
                ('post_body', models.TextField()),
                ('slug', models.SlugField()),
                ('resource_key', models.CharField(max_length=50, unique=True)),
                ('archived', models.BooleanField(default=False)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.BooleanField(default=False)),
                ('resource_key', models.CharField(max_length=50, unique=True)),
                ('archived', models.BooleanField(default=False)),
                ('date_rated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('resource_key', models.CharField(max_length=50, unique=True)),
                ('archived', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('resource_key', models.CharField(max_length=50, unique=True)),
                ('archived', models.BooleanField(default=False)),
                ('date_replied', models.DateTimeField(auto_now_add=True)),
                ('replied_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='posts.Comment')),
            ],
        ),
    ]
