# Generated by Django 2.2.3 on 2019-07-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190725_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read_duration',
            field=models.CharField(default='0 min', max_length=6),
        ),
    ]
