# Generated by Django 2.2.3 on 2019-07-27 18:49

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_read_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_heading_image',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.unique_photo_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='read_duration',
            field=models.CharField(default='0 min', max_length=10),
        ),
    ]
