# Generated by Django 2.2.3 on 2019-07-28 12:43

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='profile_avatars/default_avatar.png', upload_to=users.models.unique_photo_path),
        ),
    ]
